server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        url: ${AUTH_DATABASE_URL}
        username: ${AUTH_DATABASE_USERNAME}
        password: ${AUTH_DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
            jakarta:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
    mail:
        host: smtp.yandex.ru
        port: 465
        username: ${AUTH_MAIL_USERNAME}
        password: ${AUTH_MAIL_PASSWORD}
        protocol: smtps
        default-encoding: UTF-8
RedNet:
    app:
        passwordEncoderStrength: 10
        accessTokenCookieName: rednet-jwt-access
        accessTokenExpirationMs: 1800000
        accessTokenPath: /api
        refreshTokenCookieName: rednet-jwt-refresh
        refreshTokenExpirationMs: 180000000
        refreshTokenPath: /api/auth
        email:
            verificationRefreshTokenCookieName: rednet-evt-refresh
            verificationRefreshTokenExpirationMs: 300000
            verificationRefreshTokenPath: /api/auth
            verificationTokenExpirationMs: 150000
            verificationRefreshTokenActivationMs: 70000
            verificationLink: http://localhost:8080/api/auth/verify-email?token=
            verifiedRedirectLink: http://localhost:8080/api/test
            verificationSubject: RedNet Email Verification
        jwt:
            secretKey: ${AUTH_JWT_SECRET_KEY}