server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        url: ${USER_SERVICE_DATABASE_URL}
        username: ${USER_SERVICE_DATABASE_USERNAME}
        password: ${USER_SERVICE_DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database: postgresql
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
            jakarta:
                persistence:
                    sharedCache:
                        mode: ENABLE_SELECTIVE
    mail:
        host: smtp.yandex.ru
        port: 465
        username: ${USER_SERVICE_MAIL_USERNAME}
        password: ${USER_SERVICE_MAIL_PASSWORD}
        protocol: smtps
        default-encoding: UTF-8
RedNet:
    app:
        passwordEncoderStrength: 10
        email:
            verificationRefreshTokenCookieName: rednet-evt-refresh
            verificationRefreshTokenExpirationMs: 300000
            verificationRefreshTokenPath: /api/auth
            verificationTokenExpirationMs: 150000
            verificationRefreshTokenActivationMs: 70000
            verificationLink: http://localhost:9000/api/auth/verify-email?token=
            verificationSubject: RedNet Email Verification